name: Deploy VitePress site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# 设置必要的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 并发控制
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run docs:build

      # 添加 .nojekyll 文件防止Jekyll处理
      - name: Create .nojekyll
        run: touch .vitepress/dist/.nojekyll

      - name: Verify build output
        run: |
          ls -la .vitepress/dist
          [ -f .vitepress/dist/index.html ] || exit 1

      # 使用官方上传组件
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4